### PR TITLE
Prevent invalid ratio calculation and fitting

### PR DESCRIPTION
**Pull request by zarko-tg**

### CODE REVIEW

**Comment by zarko-tg** [comment]
Demo of the problem here: http://codepen.io/zarko/pen/avmGZV

**Comment by andreialecu** [comment]
The problem here is that when the text is in a container that is hidden with `display:none`, `offsetHeight` and `offsetWidth` will return 0, since it will be set invisible as well.

+1 for this fix. I also stumbled upon this bug.

**Comment by MonkeyDo** [comment]
This solved a problem I had when using this with Ionic and cached pages.

Please do merge in !

**Comment by patrickmarabeas** [comment]
Sorry guys! I've been swamped - will get to releasing a new version with latest round of fixes ASAP!

**Pull request merged**
